name: Cut Tag

on:
  workflow_dispatch:
    inputs:
      version-level:
        description: "Version bump level"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  id-token: write
  contents: write

jobs:
  cut-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}

      - uses: p6m-actions/js-pnpm-setup@v1

      - uses: p6m-actions/js-pnpm-cut-tag@v1
        with:
          version-level: {% raw %}${{ inputs.version-level }}{% endraw %}
